/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8CKrdbUsUmz
 */
import {Button} from "@/components/ui/button"
import {Input} from "@/components/ui/input"
import {DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger} from "@/components/ui/dropdown-menu"
import AppCard from "@/components/component/AppCard";
import { JSX, SVGProps } from "react";

export function Repo() {
    const apps = [
        {title: "File System", id: "filesystem", description: "Collection of commands related to file system"},
        {title: "Text Utilities", id: "textutilities", description: "Collection of commands related to text manipulation"},
        {title: "Date and Time", id: "dateandtime", description: "Collection of commands related to date or time"},
        {title: "Unit Converter", id: "unitconverter", description: "Collection of commands related to unit conversion"},
    ];

    return (
        <main className="h-screen flex flex-col gap-6 p-4 md:gap-8 md:p-6 bg-gray-900 text-white">
            <div className="max-w-6xl w-full mx-auto flex items-center gap-4">
                <form className="flex-1">
                    <Input className="bg-gray-800 text-white" placeholder="Search apps..."/>
                    <Button className="sr-only" type="submit">
                        Submit
                    </Button>
                </form>
                <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                        <Button className="ml-auto text-white" variant="ghost">
                            <FilterIcon className="w-4 h-4 mr-2"/>
                            Filter by Shell
                        </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end" className="bg-gray-800 text-white">
                        <DropdownMenuItem className="text-white">Bash</DropdownMenuItem>
                        <DropdownMenuItem className="text-white">Zsh</DropdownMenuItem>
                        <DropdownMenuItem className="text-white">Fish</DropdownMenuItem>
                    </DropdownMenuContent>
                </DropdownMenu>
            </div>
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 max-w-6xl w-full mx-auto">
                {apps.map(value => {
                    return <AppCard key={value.id} title={value.title} id={value.id}
                                    description={value.description}/>;
                })}
            </div>
        </main>
    )
}

function FilterIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"/>
        </svg>
    )
}